export const locations = [
  { code: "Y005", name: "--- 銀座・有楽町・新橋・豊洲・月島エリア ---" },
  { code: "XA36", name: "豊洲" },
  { code: "X015", name: "有楽町" },
  { code: "X026", name: "月島" },
  { code: "X005", name: "銀座" },
  { code: "X010", name: "東銀座" },
  { code: "X020", name: "新橋" },
  { code: "X021", name: "汐留" },
  { code: "X025", name: "築地" },
  { code: "XA33", name: "新富町" },
  { code: "X022", name: "虎ノ門" },
  { code: "XA32", name: "日比谷" },
  { code: "XA34", name: "勝どき" },
  { code: "XA35", name: "晴海" },
  { code: "XA37", name: "霞が関" },
  { code: "XA38", name: "神谷町" },
  { code: "XA39", name: "御成門" },
  { code: "XA3A", name: "内幸町" },

  { code: "Y010", name: "--- 東京・大手町・日本橋・人形町エリア ---" },
  { code: "X030", name: "丸の内" },
  { code: "X035", name: "日本橋" },
  { code: "X040", name: "八重洲" },
  { code: "XA2P", name: "大手町" },
  { code: "XA2Q", name: "三越前" },
  { code: "XA2R", name: "新日本橋" },
  { code: "XA2S", name: "人形町" },
  { code: "XA2T", name: "水天宮前" },
  { code: "XA2U", name: "京橋・宝町" },
  { code: "XA2V", name: "八丁堀" },
  { code: "XA2W", name: "茅場町" },
  { code: "XA2X", name: "小伝馬町" },
  { code: "XA2Y", name: "馬喰町" },
  { code: "XA2Z", name: "浜町" },
  { code: "XA30", name: "東日本橋" },
  { code: "XA31", name: "馬喰横山" },

  { code: "Y110", name: "--- 八王子・立川エリア ---" },
  { code: "X222", name: "立川" },
  { code: "XA7N", name: "立川市その他" },

  { code: "Y089", name: "--- 昭島エリア ---" },
  { code: "XA7H", name: "昭島"},

];