export const locations = [
  { code: "Y005", name: "--- 銀座・有楽町・新橋・豊洲・月島エリア ---" },
  { code: "X005", name: "銀座" },
  { code: "X010", name: "東銀座" },
  { code: "X015", name: "有楽町" },
  { code: "X020", name: "新橋" },
  { code: "X021", name: "汐留" },
  { code: "X022", name: "虎ノ門" },
  { code: "X025", name: "築地" },
  { code: "X026", name: "月島" },
  { code: "XA32", name: "日比谷" },
  { code: "XA33", name: "新富町" },
  { code: "XA34", name: "勝どき" },
  { code: "XA35", name: "晴海" },
  { code: "XA36", name: "豊洲" },
  { code: "XA37", name: "霞が関" },
  { code: "XA38", name: "神谷町" },
  { code: "XA39", name: "御成門" },
  { code: "XA3A", name: "内幸町" },
  
  { code: "Y010", name: "--- 東京・大手町・日本橋・人形町エリア ---" },
  { code: "X030", name: "丸の内" },
  { code: "X035", name: "日本橋" },
  { code: "X040", name: "八重洲" },
  { code: "XA2P", name: "大手町" },
  { code: "XA2Q", name: "三越前" },
  { code: "XA2R", name: "新日本橋" },
  { code: "XA2S", name: "人形町" },
  { code: "XA2T", name: "水天宮前" },
  { code: "XA2U", name: "京橋・宝町" },
  { code: "XA2V", name: "八丁堀" },
  { code: "XA2W", name: "茅場町" },
  { code: "XA2X", name: "小伝馬町" },
  { code: "XA2Y", name: "馬喰町" },
  { code: "XA2Z", name: "浜町" },
  { code: "XA30", name: "東日本橋" },
  { code: "XA31", name: "馬喰横山" },

  { code: "Y110", name: "--- 八王子・立川エリア ---" },
  { code: "X220", name: "八王子" },
  { code: "X221", name: "日野" },
  { code: "X222", name: "立川" },
  { code: "XA73", name: "豊田" },
  { code: "XA78", name: "高尾山" },
  { code: "XA79", name: "西八王子" },
  { code: "XA7A", name: "山田" },
  { code: "XA7B", name: "八王子みなみ野" },
  { code: "XA7E", name: "日野市その他" },
  { code: "XA7F", name: "八王子市その他" },
  { code: "XA7N", name: "立川市その他" },

  { code: "Y089", name: "--- 昭島エリア ---" },
  { code: "XA7G", name: "玉川上水"},
  { code: "XA7H", name: "昭島"},
  { code: "XA7I", name: "拝島"},
  { code: "XA7J", name: "福生"},
  { code: "XA7K", name: "羽村"},
  { code: "XA7L", name: "小作"},
  { code: "XA7M", name: "秋川"},
  { code: "XA7O", name: "羽村市その他"},
  { code: "XA7P", name: "あきる野市その他"},
  { code: "XA7Q", name: "東大和"},
  { code: "XA7R", name: "小川"},
  { code: "XA98", name: "青梅"},
  { code: "XA99", name: "河辺"},
  { code: "XA9A", name: "奥多摩"},

];